Dev
addod19/backgrounds-gradients pull request #1
Opened 2019-06-21 05:53 UTC by addod19

2019-06-21 13:30 UTC, Torres-ssf requested changes
Hi there @addod19. You did a great job in this project. But before I give 👍 we need to do some changes to match Microverse guidelines.
- [ ] The most important content in your page must be inside a `main` tag. Your `div id="my"` is a good candidate to be a `main` tag. Kindly change this div tag to a main tag instead.

- [ ] Your main background image is a bit off from the right position. I reviewed your code and suggested a change to fix that.

- [ ] For this project sake, the 3 main sentences must be images. In the original page, those 3 main sentences are actually images. Those images must be loaded in a div tag, using the background, just like you did in the main big image. You can get the 3 image sentences in the original page. Also, all the 3 sentences have to be links. Use a div tags to load the images (no need for the img tag) an put inside an anchor tags.

- [ ] In this project the `footer` starts at your `div class="myfooter"`. Divide the footer with two containers.

- [ ] The four promo images from the first part of the footer must be loaded the same way of the 3 main sentences. Use a div tag for the image and load them using the background. Each one of these images has to be links

Please kindly make these changes and submit for code review again!

2019-06-21 13:30 UTC, Torres-ssf commented on assets/css/style.css
> +    background-image: url(https://web.archive.org/web/20140301004302im_/http://images.apple.com/v/home/as/images/your_verse_hero.jpg);
Your background image is little off from the right position. In order to fix that, please replace the `background-image` with this one: `background: url(https://web.archive.org/web/20140301004302im_/http://images.apple.com/v/home/as/images/your_verse_hero.jpg) 0 100%;`

2019-06-23 20:46 UTC, bellom approved these changes
Hi @addod19, 
## Great job, Congratulation :+1: 
_It will be great to practice the right way of making using of nav, main and footer tag._
In your code i could see you have `main and footer tag inside div`, it shouldn't be like that, kindly check out this [link](https://www.themelocation.com/best-html5-practices) and correct it.
After the corrction you can merge to master and submit your project completion form.

2019-06-23 20:55 UTC, addod19 commented
Okay....I will do just that and submit the project completion form as
requested.Thanks

On Sun, 23 Jun 2019 at 8:46 PM, Oluwaseun Bello <notifications@github.com>
wrote:

> *@bellom* approved this pull request.
>
> Hi @addod19 <https://github.com/addod19>,
> Great job, Congratulation 👍
>
> *It will be great to practice the right way of making using of nav, main
> and footer tag.*
> In your code i could see you have main and footer tag inside div, it
> shouldn't be like that, kindly check out this link
> <https://www.themelocation.com/best-html5-practices> and correct it.
> After the corrction you can merge to master and submit your project
> completion form.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/addod19/backgrounds-gradients/pull/1?email_source=notifications&email_token=ALB5HELMKNLPSWCOXRXEQN3P37OJDA5CNFSM4H2MCMBKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4LL5BA#pullrequestreview-253148804>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALB5HEN6ET42DH7NOIMVMELP37OJDANCNFSM4H2MCMBA>
> .
>

2019-06-23 20:55 UTC, bellom commented
:+1:

2019-06-23 22:04 UTC, merged